version: "3"

services:
  db:
    image: postgres
    env_file: ./server/.env
    ports:
      - 5432:5432
    volumes:
      - ./dbdata:/var/lib/postgresql/data
  server:
    build: ./server
    ports:
      - 5000:5000
  app:
    build: ./app
    ports:
      - 8080:8080
    depends_on:
      - server
  # nginx:
  #   image: nginx
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #     - /etc/letsencrypt/:/etc/letsencrypt/
  #   ports:
  #     - 80:80
  #     - 443:443
  #   depends_on:
  #     - db
  #     - app
  #     - server
