version: "3"

services:
  db:
    image: postgres
    env_file: ./server/.env
    ports:
      - 5432:5432
    volumes:
      - ./dbdata:/var/lib/postgresql/data

  nginx:
    image: nginx
    restart: unless-stopped
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
      - server
      - db
      - certbot
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''

  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  node:
    build: ./server
    ports:
      - 5000:5000

  app:
    build: ./app
    ports:
      - 8080:8080
    depends_on:
      - server
